theme: jekyll-theme-minimal
logo: /www/images/genriver_logo.svg
title: GenRiver3
description: A generic river model on river flow

# Navigation Menus
header_navigation:
  - title: Documentation
    url: /docs/

  - title: Themes
    url: https://desiredpersona.com/themes/

  - title: About
    url: /about/

  - title: Blog
    url: /archive/

  - title: Contact
    url: mailto:you@example.com
