# theme: jekyll-theme-minimal
theme: minima
# remote_theme: pages-themes/leap-day@v0.2.0
# plugins:
#  - jekyll-remote-theme
title: GenRiver3
description: A generic river model on river flow
logo: /www/images/genriver_logo.svg
google_analytics:
